# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=30)),
                ('series', models.CharField(max_length=30)),
                ('manufacturer_country', models.CharField(max_length=30)),
                ('options', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Dye',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=15)),
                ('colour', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.FloatField(max_length=10)),
                ('number_of_cylinders', models.IntegerField()),
                ('valves', models.IntegerField()),
                ('rpm', models.IntegerField()),
                ('horsepower', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Wheels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30)),
                ('kind', models.CharField(max_length=30)),
                ('diagonal', models.FloatField(max_length=3)),
                ('width', models.FloatField(max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.ManyToManyField(to='car.Dye'),
        ),
        migrations.AddField(
            model_name='car',
            name='engine',
            field=models.ManyToManyField(to='car.Engine'),
        ),
        migrations.AddField(
            model_name='car',
            name='wheels',
            field=models.ManyToManyField(to='car.Wheels'),
        ),
    ]
