# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='color',
        ),
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='car.Dye'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='car',
            name='engine',
        ),
        migrations.AddField(
            model_name='car',
            name='engine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='car.Engine'),
            preserve_default=False,
        ),
    ]
