# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_engine_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'KEEEEEEK', 'verbose_name_plural': 'KEEEEEKS'},
        ),
        migrations.AlterField(
            model_name='engine',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='engine',
            name='number_of_cylinders',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
