# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 15:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=30)),
                ('series', models.CharField(max_length=30)),
                ('body', models.CharField(blank=True, max_length=10, null=True)),
                ('manufacturer_country', models.CharField(blank=True, max_length=30, null=True)),
                ('cost', models.FloatField(blank=True, max_length=20, null=True)),
                ('options', models.TextField(blank=True, max_length=300, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dye',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(blank=True, max_length=15, null=True)),
                ('colour', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('capacity', models.FloatField(max_length=10)),
                ('number_of_cylinders', models.IntegerField(blank=True, null=True)),
                ('valves', models.IntegerField(blank=True, null=True)),
                ('rpm', models.IntegerField(blank=True, null=True)),
                ('horsepower', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wheels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30)),
                ('kind', models.CharField(max_length=30)),
                ('diagonal', models.FloatField(blank=True, max_length=3, null=True)),
                ('width', models.FloatField(blank=True, max_length=3, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Dye'),
        ),
        migrations.AddField(
            model_name='car',
            name='engine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Engine'),
        ),
        migrations.AddField(
            model_name='car',
            name='wheels',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Wheels'),
        ),
    ]
